ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black --line-length 88
      additional_dependencies:
        - --override-channels
        - --channel
        - conda-forge
        - black=22.3.0
      language: conda
      types:
        - python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --exclude-file=.codespellignorelines
          - --ignore-words=.codespellignorewords
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.4
  #   hooks:
  #     - id: flake8
