name: bot-delete-old-runs

on:
#   schedule:
#     - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          path: cf-scripts

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: cf-scripts/conda-lock.yml
          environment-name: cf-scripts
          condarc-file: cf-scripts/autotick-bot/condarc

      - name: delete runs
        run: |
          cd cf-scripts
          python autotick-bot/delete_old_runs.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
