name: bot-make-graph

on:
  workflow_dispatch: null
  schedule:
    - cron:  '0 */4 * * *'

concurrency: bot-make-graph

jobs:
  bot-make-graph:
    name: bot-make-graph
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          path: cf-scripts

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ vars.PYVER }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: cf-scripts

      - name: do local setup and stop me if needed
        run: |
          pushd cf-scripts
          source autotick-bot/local_setup.sh
          python autotick-bot/stop_me_if_needed.py
          popd

      - name: install bot code
        if: success() && ! env.CI_SKIP
        run: |
          source cf-scripts/autotick-bot/install_bot_code.sh
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}

      - name: make graph
        if: success() && ! env.CI_SKIP
        run: |
          pushd cf-graph

          conda-forge-tick --run 1

          popd
        env:
          USERNAME: regro-cf-autotick-bot
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}

      - name: deploy
        if: github.ref == 'refs/heads/master' && always() && ! env.CI_SKIP
        run: |
          pushd cf-graph

          export CIRCLE_BUILD_URL="https://github.com/regro/cf-scripts/actions/runs/${RUN_ID}"
          export CIRCLE_BUILD_NUM="actually-actions-${RUN_ID}"
          conda-forge-tick --run -1

          popd
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}
          RUN_ID: ${{ github.run_id }}

      - name: trigger next job
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385
        if: github.ref == 'refs/heads/master' && ! cancelled() && ! failure() && ! env.CI_SKIP
        with:
          workflow: bot-make-graph
          ref: ${{ github.event.ref }}
          token: ${{ secrets.AUTOTICK_BOT_TOKEN }}

      - name: bump on fail
        if: github.ref == 'refs/heads/master' && failure() && ! env.CI_SKIP
        run: |
          export ACTION_URL="https://github.com/regro/cf-scripts/actions/runs/${RUN_ID}"
          python cf-scripts/autotick-bot/bump_bot_team.py
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          ACTION_NAME: ${{ github.workflow }}
