name: bot-delete-old-runs

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: ${{ vars.PYVER }}
          use-mamba: true
          environment-file: environment.yml
          activate-environment: cf-scripts

      - name: delete runs
        shell: bash -l {0}
        run: |
          python autotick-bot/delete_old_runs.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
